config/routes.rb
Rails.application.routes.draw do

	resources :notifications

  get 'messages/create'
	get 'messages/destroy'
	
  get 'chats/show', to: 'chat_rooms#show'
	get 'chats', to: 'chat_rooms#index'

	post 'messages/create'
	post 'messages/destroy'
	
	resources :sessions, only: [:new, :create, :destroy]
	
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
	
	resources :users
  resources :categories

	resources :posts do
    resources :comments
  end

  resources :comments do
    resources :comments
	end
	
	resources :friendships

	post 'friendships/accept', to: 'friendships#accept'
	post 'friendships/reject', to: 'friendships#reject'
	
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
	get 'logout', to: 'sessions#destroy', as: 'logout'
	
	get 'admin', to: 'users#index', as: 'admin'

	root 'posts#index'

	post 'upvote', to: 'votes#upvote', as: 'upvote'
	post 'downvote', to: 'votes#downvote', as: 'downvote'

	post 'comments/new', to: 'comments#create'

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
	
	belongs_to :commentable, polymorphic: true
	has_many :comments, as: :commentable
	
	validates :text, length: { minimum: 1, maximum: 500 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :find_commentable, only: :create

	def new
    @comment = Comment.new
  end

	def create
		unless current_user
			flash[:alert] = 'You must be logged in to comment'
			return redirect_to post_path(find_post(@commentable))
		end
		@commentable.comments.build(comment_params)
		if @commentable.save
			unless current_user == (@commentable.class == Post ? @commentable.author : @commentable.user)
				Notification.new(
					body: current_user.nick.capitalize + ' sent you a comment', 
					user: @commentable.class == Post ? @commentable.author : @commentable.user,
					link: url_for( find_post(@commentable) )
				).save
				flash[:success] = 'Comment sent'
			end
		else
			flash[:alert] = 'Something went wrong, please try again'
		end
		redirect_to post_path(find_post(@commentable))
	end
	
	def destroy
		comment = Comment.find_by(id: params[:id])
		post = find_post(comment.commentable) 
		unless current_user
			return redirect_to post_path(post)
		end
		unless comment.user == current_user || current_user.admin
			return redirect_to post_path(post)
		end
		comment.delete
		flash[:success] = 'Comment deleted'
		redirect_to post_path(post)
	end

	private

    def comment_params
      params.require(:comment).permit(:text, :user_id)
    end

		def find_commentable
      if params[:comment][:comment_id]
        @commentable = Comment.find_by(id: params[:comment][:comment_id]) 
      elsif params[:comment][:post_id]
        @commentable = Post.find_by(id: params[:comment][:post_id])
			end
		end
		
		def find_post(commentable)
			post = commentable
			while post.class != Post do
				post = post.commentable
			end
			post
		end

end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<li class="border list-group-item mt-3" style="font-size:13px">
	<div class="row">
		<div class="text-left col">
			<b>
				<%= link_to comment.user.nick, user_path(comment.user), class: 'text-dark' %>
			</b>
		</div>

		<% if current_user%>
			<% if current_user == comment.user || (current_user && current_user.admin) %>
				<div class="text-right mr-3">
					<p>
						<%= link_to 'Delete', comment_path(comment), 
							method: :delete, class: 'text-muted' %>
					</p>	
				</div>
			<% end %>
			
			<div class="text-right mr-3" id="displayForm<%=comment.id.to_s%>">
					<p>
						<a class="text-muted">Reply</a>
					</p>
			</div>
		<% end %>
	</div>
  <div class=""><%= comment.text %><div>

	<% if current_user %>

		<div id="comment">
		</div>

		<div id="commentForm<%= comment.id %>" class="container mt-2" style="display:none">
			<%= render partial: 'comments/form', 
				locals: { 
					:comment => Comment.new, 
					:comment_id => comment.id, 
					:is_post => false, 
					:user_id => current_user.id,
					:post_id => local_assigns[:post_id] 
					} %>
		</div>

	<% end %>

  <ul class="list-group">
    <%= render partial: 'comments/comment', collection: comment.comments %>
  </ul>
	
	<script>
		$('#displayForm<%= comment.id %>').click(function (){
			$('#commentForm<%= comment.id %>').toggle();
		});
	</script>

</li>

app/views/comments/_form.html.erb
<%= bootstrap_form_for comment do |f| %>
	<%= f.text_area :text, hide_label: true %>

	<%= f.hidden_field :post_id, value: local_assigns[:post_id] %>

	<% unless local_assigns[:is_post] %>
		<%= f.hidden_field :comment_id, value: local_assigns[:comment_id] %>
	<% end %>

	<%= f.hidden_field :user_id, value: current_user.id %>
	
	<%= f.submit local_assigns[:is_post] ? "Comment" : "Send reply", class: 'btn btn-sm btn-primary'  %>

<% end %>