config/routes.rb
Rails.application.routes.draw do

	resources :notifications

  get 'messages/create'
	get 'messages/destroy'
	
  get 'chats/show', to: 'chat_rooms#show'
	get 'chats', to: 'chat_rooms#index'

	post 'messages/create'
	post 'messages/destroy'
	
	resources :sessions, only: [:new, :create, :destroy]
	
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
	
	resources :users
  resources :categories

	resources :posts do
    resources :comments
  end

  resources :comments do
    resources :comments
	end
	
	resources :friendships

	post 'friendships/accept', to: 'friendships#accept'
	post 'friendships/reject', to: 'friendships#reject'
	
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
	get 'logout', to: 'sessions#destroy', as: 'logout'
	
	get 'admin', to: 'users#index', as: 'admin'

	root 'posts#index'

	post 'upvote', to: 'votes#upvote', as: 'upvote'
	post 'downvote', to: 'votes#downvote', as: 'downvote'

	post 'comments/new', to: 'comments#create'

end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	validates :email, presence: true, uniqueness: true, length: { maximum: 100 }
	validates :nick, presence: true, uniqueness: true, length: { minimum: 4, maximum: 20 }
	validates :password, presence: true, length: { minimum: 8, maximum: 30 }
	validates :name, length: { minimum: 3, maximum: 200 }
	validates :summary, length: { maximum: 1000 }

	has_many :votes, :dependent => :delete_all
	has_many :liked_posts, through: :votes
	
	has_many :notifications

	has_many :comments, :dependent => :delete_all
	has_many :commenters, through: :comments

	has_many :sent_friendships, :class_name => 'Friendship', :foreign_key => 'sender_id', :dependent => :destroy
  has_many :received_friendships, :class_name => 'Friendship', :foreign_key => 'receiver_id', :dependent => :destroy

	has_one_attached :image

	# Email regex validation
	validates_format_of :email, :with => /\A\S+@.+\.\S+\z/
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
  before_action :set_user, only: [:show, :edit, :update, :destroy]

	def index
		if !user_admin?
			flash[:alert] = 'Gotcha, dirty little cheater'
			redirect_to root_path
		else
			@users = User.all
		end
  end

	def show
		@requested_friendships = Friendship.where(receiver: @user, accepted: false)
		@friends = Friendship.where(receiver: @user, accepted: true)
			.or(Friendship.where(sender: @user, accepted: true))
		@valid_friendship = (Friendship.where(sender: current_user , receiver: @user)
			.or(Friendship.where(sender: @user, receiver: current_user))).empty? && @user != current_user
		@posts = Post.where(author: @user).order(created_at: :desc)
	end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
		if @user.save
			flash[:success] = 'Welcome aboard to Link Bay!'
			session[:user_id] = @user.id
			redirect_to @user
		else
			render :new 
		end
  end

	def update
		if @user != current_user
			redirect_to root_path
		elsif @user.update(user_params)
			flash[:success] = 'Your account was succesfully updated'
			redirect_to @user 
		else
			render :edit 
		end
  end

  def destroy
		@user.destroy
		flash[:alert] = 'We are sad that you are leaving...'
    redirect_to root_path
  end

  private

		def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :name, :summary, :admin, :nick, :image_link)
		end
		
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="text-center">
	<h1>Editing profile</h1>
	<p>Remember to follow our guidelines, or just don't be offensive</p>
</div>

<div class="text-center mt-4">
	<%= bootstrap_form_for @user, url: user_path(@user) do |f| %>
		<%= f.email_field :email %>
		<%= f.text_field :name %>
		<%= f.text_area :summary, label: 'Bio' %>
		<%= f.text_field :image_link, label: 'Profile picture (URL)' %>
		
		<br>
		<p>Password is required for making changes to your profile</p>
		<%= f.password_field :password %>
		<br>

		<div class="d-flex justify-content-center col">
			<%= f.submit "Change profile", class: ' btn btn-success' %>
		</div>
	<% end %>
</div>

app/views/users/index.html.erb
<h1 class="text-center">Admin panel</h1>

<div class="text-center">
  <%= button_to 'Categories', categories_path, class: 'btn btn-primary', method: :get %>
</div>

<table class="table mt-3">
  <thead>
    <tr>
      <td><b>Name</b></td>
      <td><b>Permissions</b></td>
      <td><b>Nickname</b></td>
      <td></td><td></td>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.admin ? 'Admin' : 'User' %></td>
        <td><%= user.nick %></td>
        <td><%= button_to 'Profile', user, method: :get, class: 'btn btn-primary btn-sm' %></td>
        <td><%= button_to 'Ban', user, method: :delete, data: { confirm: "Are you sure you want to delete this user's account?" }, class: 'btn btn-primary btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<div class="text-center">
	<h1>Sign Up</h1>
	<p>Remember to follow our guidelines, or just don't be offensive</p>
</div>

<div class="text-center mt-4">
	<%= bootstrap_form_for @user, url: users_path do |f| %>
		<%= f.text_field :nick, label: 'Nickname (unique for every user)' %>
		<%= f.email_field :email %>
		<%= f.password_field :password %>
		<%= f.password_field :password_confirmation %>
		<%= f.text_field :name %>
		<p></p>
		<div class="d-flex justify-content-center col">
			<%= f.submit "Create account", class: ' btn btn-success', data: { confirm: "You may not change your nickname after you've selected it, proceed?" } %>
		</div>
	<% end %>
</div>

app/views/users/show.html.erb
<h1 class="text-center"><%= @user.nick.capitalize + "'s" %> Profile</h1>

<div class="row mt-3 border p-3">

	<div class="col-6" style="height:200px;">
		<img src="<%= (!@user.image_link.nil? && !@user.image_link.empty?) ? 
			@user.image_link : empty_user_image %>" class="rounded mx-auto d-block img-fluid"
			style="width:auto;max-height:100%;">
	</div>

	<div class="container col-6 col" style="height:200px;">

		<div id="list" class="row">
			<div class="table-responsive table-borderless col-md-12">
			
				<table class="table" cellspacing="0" cellpadding="0">
					<tbody>
						<tr>
							<td class="text-muted">Name:</td>
							<td><%= @user.name%></td>
						</tr>
						<tr>
							<td class="text-muted">Email:</td>
							<td><%= @user.email%></td>
						</tr>
						<tr>
							<td class="text-muted">Nick:</td>
							<td><%= @user.nick%></td>
						</tr>
						<tr>
							<td class="text-muted">Position:</td>
							<td><%= @user.admin? ? 'Administrator' : 'User' %></td>
						</tr>
						<tr>
							<td class="text-muted">Joined:</td>
							<td><%= @user.created_at.strftime("%-d/%-m/%y") %></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<% if current_user == @user || (current_user && current_user.admin) %>
		<div class="col d-flex justify-content-<%= (current_user && @valid_friendship) ?  "left" : "center" %> mt-4">
			<%= button_to 'Edit profile', edit_user_path(@user), method: :get, class: "btn btn-primary"%>
		</div>
	<% end %>
	<% if current_user && @valid_friendship %>
		<div class="mt-4 col">
			<%= bootstrap_form_for :friendship, url: '/friendships' do |f| %>
				<%= f.hidden_field :sender_id, value: current_user.id %>
				<%= f.hidden_field :receiver_id, value:	@user.id %>
				<div class="text-<%= (current_user == @user || (current_user && current_user.admin)) ?  "right" : "center" %>">
					<%= f.submit 'Send friendship request', class: 'btn btn-primary' %>
				</div>
			<% end %>
		</div>
	<% end %>
</div>

<% if @user.summary %>
	<div class="container mt-3">
		<hr />
		<h4 class="text-center">Bio</h4>
			<div class="text-center">
				<%= @user.summary %>
			</div>
		<hr />
	</div>
<% end %>

<% if current_user == @user && !@requested_friendships.empty? %>
	<div class="container mt-3">
		<h4 class="text-center"> Friendship requests: </h4>
		<table class="table" cellspacing="0" cellpadding="0">
			<tbody>
				<tr>
				<% @requested_friendships.each do |friendship| %>
						<td class="row">
							
							<div class="col-8">
								<h5>
									<%= friendship.sender.nick %>
								</h5>
							</div>

							<div class="col-2">
								<%= bootstrap_form_for :friendship, url: '/friendships/accept' do |f| %>
									<%= f.hidden_field :sender_id, value: @user.id %>
									<%= f.hidden_field :friendship_id, value: friendship.id %>
									<%= f.submit 'Accept', class: 'btn btn-sm float-right text-white' %>
								<% end %>
							</div>
							
							<div class="col-2">
								<%= bootstrap_form_for :friendship, url: '/friendships/reject' do |f| %>
									<%= f.hidden_field :friendship_id, value: friendship.id %>
									<%= f.hidden_field :receiver_id, value:	current_user.id %>
									<%= f.submit 'Reject', class: 'btn btn-sm float-right text-white' %>
								<% end %>
							</div>
						</td>
					<% end %>
				</tr>
			</tbody>
		</table>
	</div>
<% end %>

<div class="container mt-5">
	<h4 class="text-center"> <%= @user.nick.capitalize %>'s friends: </h4>

	<table class="table" cellspacing="0" cellpadding="0">
		<tbody>
			<% if @friends.empty? %>
				<tr><td class="text-center">No friends found</td></tr>
			<% end %>
			<% @friends.each do |friendship| %>
			<tr>
				<td>
					<div class="row">
						<% target_user = friendship.sender %>
						<% if friendship.sender == @user %>
							<% target_user = friendship.receiver %>
						<% end %>
						<div class="col <%= (@user == current_user || target_user == current_user) ? "text-left" : "text-center" %>">
							<a href="<%= user_path(target_user) %>" class=" no-text-decoration">
								<h6>
									<%= target_user.nick %>
								</h6>
							</a>
						</div>
						<% if @user == current_user || target_user == current_user %>
							<div class="col text-right">
								<%= button_to 'End friendship', friendship, :class => "btn btn-sm text-white", :method => :delete %>
							</div>
						<% end %>
					</div>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

<div class="container mt-5">
	<h4 class="text-center"> <%= @user.nick.capitalize %>'s posts: </h4>

	<table class="table" cellspacing="0" cellpadding="0">
		<tbody>
			<% @posts.each do |post| %>
			<tr>
				<td>
						<a href="<%= post_path(post) %>" class="no-text-decoration">
							<div class=" p-0">
								<h6 class="text-center">
									<%= post.title %>
								</h6>
							</div>
						</a>
					</div>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>