config/routes.rb
Rails.application.routes.draw do

	resources :notifications

  get 'messages/create'
	get 'messages/destroy'
	
  get 'chats/show', to: 'chat_rooms#show'
	get 'chats', to: 'chat_rooms#index'

	post 'messages/create'
	post 'messages/destroy'
	
	resources :sessions, only: [:new, :create, :destroy]
	
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
	
	resources :users
  resources :categories

	resources :posts do
    resources :comments
  end

  resources :comments do
    resources :comments
	end
	
	resources :friendships

	post 'friendships/accept', to: 'friendships#accept'
	post 'friendships/reject', to: 'friendships#reject'
	
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
	get 'logout', to: 'sessions#destroy', as: 'logout'
	
	get 'admin', to: 'users#index', as: 'admin'

	root 'posts#index'

	post 'upvote', to: 'votes#upvote', as: 'upvote'
	post 'downvote', to: 'votes#downvote', as: 'downvote'

	post 'comments/new', to: 'comments#create'

end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :category
	belongs_to :author, :class_name => "User"

	validates :title, presence: true, length: { minimum: 5, maximum: 50 }
	validates :body, length: { maximum: 10000 }
	validates :digest, length: { maximum: 140 }
	
	has_many :votes, :dependent => :delete_all
	has_many :votants, through: :votes

	has_many :commenters, through: :comments
  has_many :comments, as: :commentable, :dependent => :delete_all

	has_one_attached :image

	def approval_percentage
		if vote_sum > 0
			((vote_counter / vote_sum) * 100.0).round.to_s + ' %'
		else
			'0 %'
		end
	end

	def approval_absolute
		vote_counter >= 0 ? '+ ' + vote_counter.to_s : '- ' + (-vote_counter).to_s
	end

	def posted_at
		minute = 60
		hour = minute * 60
		day = hour * 24
		year = day * 365
		delta = Time.now - created_at
		
		if delta < minute
			'Just now'
		elsif delta < hour
			(delta / minute).round.to_s + ' minute'.pluralize((delta / minute).round) + ' ago'
		elsif delta < day
			(delta / hour).round.to_s + ' hour'.pluralize((delta / hour).round) +  ' ago'
		elsif delta < year
			(delta / day).round.to_s + ' day'.pluralize((delta / day).round) + ' ago'
		else
			created_at.strftime("%-d/%-m/%y")
		end
	end
	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :set_post, only: [:show, :edit, :update, :destroy]

	@@per_page_pagination = 5

	# -	:category means a tag for a post like 'science' or 'art'
	# -	:keywords come from the search bar, it displays any result in the database that matches
	# either a post title or body
	def index
		if params.has_key?(:category)
			@category = Category.find_by(name: params[:category])
			@posts = Post.where(category: @category)
				.order(:weight)
				.paginate(:page => params[:page], per_page: @@per_page_pagination)
		elsif params.has_key?(:keywords)
			@posts = Post.where('title LIKE ? OR body LIKE ?',
				"%#{params[:keywords]}%", "%#{params[:keywords]}%")
				.order(:weight)
				.paginate(:page => params[:page], per_page: @@per_page_pagination)
		else
			@posts = Post.order(:weight)
				.paginate(:page => params[:page], per_page: @@per_page_pagination)
		end
	end

	def show
		@post.update_attribute(:views, @post.views + 1)
	end

	def new
		unless current_user
			flash[:alert] = 'You must be logged in to post'
			return redirect_to root_path
		end
		@post = Post.new
	end

	def edit
		unless user_is_poster?
			return redirect_to posts_url
		end
	end
	
	def create
		unless current_user # && current_user.id == post_params[:user_id]
			return redirect_to root_path
		end
		@post = Post.new(post_params)
		@post.author = current_user
		@post.vote_counter = 0
		@post.vote_sum = 0
		@post.views = 0
		@post.weight = 0
		if @post.save
			flash[:success] = 'Your post has been created'
			return redirect_to @post
		else
			return render :new
		end
	end

	def update
		unless user_is_poster?
			return redirect_to posts_url
		end
		if @post.update(post_params)
			flash[:success] = 'Your post has been updated'
			return redirect_to @post
		else
			return render :edit
		end
	end

	def destroy
		unless user_is_poster?
			return redirect_to posts_url
		end
		@post.destroy
		flash[:success] = 'Your post has been deleted'
		return redirect_to posts_url
	end

	private

		def set_post
			@post = Post.find(params[:id])
		end

		def post_params
			params.require(:post).permit(:title, :body, :category_id, :image_link, :author_id, :digest)
		end

		def user_is_poster?
			unless current_user && ((@post.author == current_user) || (current_user.admin))
				return false
			end
			return true
		end
		
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="text-center">
	<h2>Edit your post</h2>

	<%= bootstrap_form_for(@post, class: 'text-right') do |f| %>
		<%= f.text_field :title %>
		<%= f.text_field :digest, label: 'Post description (140 characters)' %>
		<%= f.text_area :body %>
		<%= f.select :category_id, Category.all.collect { |cat| [cat.name, cat.id] } %>
		<%= f.file_field :image, label: 'Post image' %>
		<div class="d-flex justify-content-center col">
			<%= f.submit "Submit post", class: ' btn btn-success' %>
		</div>
	<% end %>

	<div class="d-flex justify-content-center">
		<%= button_to 'Go back', post_path(@post) , :class => "btn btn-primary mt-3", :method => :get %>
	</div>
</div>

app/views/posts/index.html.erb
<div class="row p-0">
	<div class="col-4 dropdown">
		<button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			Categories
		</button>
		<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
			<% Category.all.each do |cat| %>
				<a class="dropdown-item" href="<%= posts_path(category: cat.name) %>">
					<%= cat.name %>
				</a>
			<% end %>
		</div>
	</div>
	
	<div class="col-8">
		<%= bootstrap_form_tag url: '/', method: :get do |f| %>
			<%= f.text_field :keywords, hide_label: true, placeholder: 'Search for posts' %>
		<% end %>
	</div>
</div>



<div class="container p-0">

	<% @posts.each do |post| %>

		<a href="<%= post_path(post) %>" class="no-text-decoration">

			<div class="card flex-row flex-wrap mb-3 color-background-card" style="max-height:200px">
            
				<% if !post.image_link.nil? && !post.image_link.empty? %>
					<div class="p-0 d-none d-lg-block">
						<img src="<%= post.image_link %>" class="card-img" style="max-height:200px;max-width:200px">
					</div>
				<% end %>

				<div class="px-2 card-body ml-3 text-muted" style="position:relative">
						<h4 class="card-title text-color-dark"> <%= post.title %> </h4>
						<p class="card-text mb-5"> <%= post.digest %> </p>
						<div class="container row card-text" style="position:absolute;bottom:0">
							<div class="text-left col-8 p-0">
									<p><%= post.posted_at %></p>
							</div>
							<div class="text-right col-4 p-0">
								<p><%= post.approval_absolute %> | <%= post.approval_percentage %></p>
							</div>
						</div>
				</div>

			</div>

		</a>

	<% end %>
	
</div>

<div class="mt-3 d-flex justify-content-center">
	<%= will_paginate @posts %>
</div>

<% if current_user %>
	<div class="d-flex justify-content-center">
		<%= button_to 'Write a new post', new_post_path , class: "btn btn-primary", method: :get %>
	</div>
<% end %>

app/views/posts/new.html.erb
<div class="text-center">
	<h2>Create a new post</h2>
	<p>Remeber to follow our rules for posting</p>

	<%= bootstrap_form_for(@post, class: 'text-right') do |f| %>
		<%= f.text_field :title %>
		<%= f.text_field :digest, label: 'Post description (140 characters)' %>
		<%= f.text_area :body %>
		<%= f.select :category_id, Category.all.collect { |cat| [cat.name, cat.id] } %>
		<%= f.text_field :image_link, label: 'Post image (URL)' %>
		<div class="d-flex justify-content-center col">
			<%= f.submit "Submit post", class: ' btn btn-success' %>
		</div>
	<% end %>

	<div class="d-flex justify-content-center">
		<%= button_to 'Go back', root_path , :class => "btn btn-primary mt-3", :method => :get %>
	</div>
</div>

app/views/posts/show.html.erb
<div class="text-center col-12 color-navbar p-1 rounded">
	<h1 class="text-white"> <%= @post.title %></h1>
</div>

<div class="row mt-3">

	<div class="col-1 d-flex justify-content-center">

		<div class="row">
			<%= form_for :vote, url: '/upvote', remote: true do |f| %>
				<%= f.hidden_field :post_id, value: @post.id %>
				<%=	image_submit_tag upvote_image, style: "height:30px;outline:none;" %>
			<% end %>
		</div>

		<div class="row mt-5">
			<%= form_for :vote, url: '/downvote', remote: true do |f| %>
				<%= f.hidden_field :post_id, value: @post.id %>
				<%= image_submit_tag downvote_image, style: "height:30px;outline:none;" %>
			<% end %>
		</div>

	</div>

	<div class="col-11">
		<div class="row text-muted">
			<div class="text-left col">
				<h6>By: <%= link_to @post.author.name + ' (' + @post.author.nick + ')', user_path(@post.author) %></h6>
			</div>
			<div class="text-right col">
				<h6><%= @post.posted_at %></h6>
			</div>
		</div>

		<div class="row text-muted mt-4">
			<div id="votes" class="col text-left">
				<p>
					Votes: <%= @post.vote_counter %>
				</p>
			</div>
			<div id="votes_percentage" class="col text-right">
				<p>
					Approval: <%= @post.approval_percentage %>
				</p>
			</div>
		</div>

	</div>
</div>

<% if current_user == @post.author || (current_user && current_user.admin) %>
	<div class="row mt-3">
		<div class="text-left col-6">
			<%= button_to 'Edit post', edit_post_path(@post), method: :get, class: 'btn btn-primary' %>
		</div>
		<div class="text-right col-6">
			<%= button_to 'Delete post', post_path(@post), class: 'btn btn-primary', method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
		</div>
	</div>
<% end %>

<% if !@post.image_link.nil? && !@post.image_link.empty? %>
	<div class="mt-3 color-background-card" style="height:200px;">
		<img src="<%= @post.image_link %>" class="h-100 rounded mx-auto d-block img-fluid"
			style="width:auto;max-height:100%;">
	</div>
<% end %>

<% unless @post.digest.empty? %>
	<hr />
	<div class="mt-3">
		<h6 class="text-muted text-center">
			<%= @post.digest %>
		</h6>
	</div>
	<hr />
<% else %>
	<hr />
<% end %>

<div class="mt-3">
	<p><%= simple_format @post.body %></p>
</div>

<hr />

<div class="col text-center">
	Views: <%= @post.views %> 
</div>

<div class="container mt-3 p-0">

		<% if current_user %>
			<div class="text-center mb-1">
				Leave a comment:
			</div>
			
			<%= render partial: 'comments/form', 
						locals: { 
							:comment => Comment.new, 
							:is_post => true, 
							:user_id => current_user.id,
							:post_id => @post.id 
						} %>
		<% end %>

		<div class="container p-0">		
			<%= render partial: 'comments/comment', collection: @post.comments,
				:locals => {
					:post_id => @post.id 
				} %>
		</div>

</div>