config/routes.rb
Rails.application.routes.draw do

	resources :notifications

  get 'messages/create'
	get 'messages/destroy'
	
  get 'chats/show', to: 'chat_rooms#show'
	get 'chats', to: 'chat_rooms#index'

	post 'messages/create'
	post 'messages/destroy'
	
	resources :sessions, only: [:new, :create, :destroy]
	
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
	
	resources :users
  resources :categories

	resources :posts do
    resources :comments
  end

  resources :comments do
    resources :comments
	end
	
	resources :friendships

	post 'friendships/accept', to: 'friendships#accept'
	post 'friendships/reject', to: 'friendships#reject'
	
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
	get 'logout', to: 'sessions#destroy', as: 'logout'
	
	get 'admin', to: 'users#index', as: 'admin'

	root 'posts#index'

	post 'upvote', to: 'votes#upvote', as: 'upvote'
	post 'downvote', to: 'votes#downvote', as: 'downvote'

	post 'comments/new', to: 'comments#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :friendship

  has_many :messages, :dependent => :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
	
	belongs_to :commentable, polymorphic: true
	has_many :comments, as: :commentable
	
	validates :text, length: { minimum: 1, maximum: 500 }
end

app/models/friendship.rb
class Friendship < ApplicationRecord
	belongs_to :sender, :class_name => "User"
	belongs_to :receiver, :class_name => "User"

	has_one :chat_room, :dependent => :destroy
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :chat_room
	belongs_to :user

	validates :body, length: { minimum: 1, maximum: 200 }
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :category
	belongs_to :author, :class_name => "User"

	validates :title, presence: true, length: { minimum: 5, maximum: 50 }
	validates :body, length: { maximum: 10000 }
	validates :digest, length: { maximum: 140 }
	
	has_many :votes, :dependent => :delete_all
	has_many :votants, through: :votes

	has_many :commenters, through: :comments
  has_many :comments, as: :commentable, :dependent => :delete_all

	has_one_attached :image

	def approval_percentage
		if vote_sum > 0
			((vote_counter / vote_sum) * 100.0).round.to_s + ' %'
		else
			'0 %'
		end
	end

	def approval_absolute
		vote_counter >= 0 ? '+ ' + vote_counter.to_s : '- ' + (-vote_counter).to_s
	end

	def posted_at
		minute = 60
		hour = minute * 60
		day = hour * 24
		year = day * 365
		delta = Time.now - created_at
		
		if delta < minute
			'Just now'
		elsif delta < hour
			(delta / minute).round.to_s + ' minute'.pluralize((delta / minute).round) + ' ago'
		elsif delta < day
			(delta / hour).round.to_s + ' hour'.pluralize((delta / hour).round) +  ' ago'
		elsif delta < year
			(delta / day).round.to_s + ' day'.pluralize((delta / day).round) + ' ago'
		else
			created_at.strftime("%-d/%-m/%y")
		end
	end
	
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	validates :email, presence: true, uniqueness: true, length: { maximum: 100 }
	validates :nick, presence: true, uniqueness: true, length: { minimum: 4, maximum: 20 }
	validates :password, presence: true, length: { minimum: 8, maximum: 30 }
	validates :name, length: { minimum: 3, maximum: 200 }
	validates :summary, length: { maximum: 1000 }

	has_many :votes, :dependent => :delete_all
	has_many :liked_posts, through: :votes
	
	has_many :notifications

	has_many :comments, :dependent => :delete_all
	has_many :commenters, through: :comments

	has_many :sent_friendships, :class_name => 'Friendship', :foreign_key => 'sender_id', :dependent => :destroy
  has_many :received_friendships, :class_name => 'Friendship', :foreign_key => 'receiver_id', :dependent => :destroy

	has_one_attached :image

	# Email regex validation
	validates_format_of :email, :with => /\A\S+@.+\.\S+\z/
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
  validates :value, presence: true
end

app/helpers/application_helper.rb
module ApplicationHelper

	def pluralize(count, noun, text = nil)
  	if count != 0
    	count == 1 ? "#{noun}#{text}" : "#{noun.pluralize}#{text}"
 		end
	end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Link Bay</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>

		<script>
			 <%= yield :js %>
    </script>

		<%= favicon_link_tag asset_path('earth.png') %>

	</head>

  <body>

	<a class="text-color-clear" href="/" style="text-decoration:none">
    <nav class="navbar navbar-expand-sm navbar-dark navbar-fixed-top color-navbar">
			<nav class="pl-2">
				<img src="<%= asset_path('earth.png') %>" width="25" height="25" class="mt-2 mr-1 d-inline-block align-top" style="-webkit-filter: invert(100%) !important;" alt="">
				<b class="navbar-brand">
					LINK BAY
				</b>	
			</nav>
		</a>

			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
				<div class="navbar-nav text-color-clear no-text-decoration">
					<% if current_user %>
						<% unless current_user.notifications.empty? %>
							<a href="<%= '/notifications' %>">
								<div class="p-1 rounded-circle mt-2 mr-1 ml-1 text-center bg-white" style="height:25px;width:25px">
									<p><%= current_user.notifications.size %></p>
								</div>
							</a>
						<% end %>
						<%= link_to 'Profile', '/users/' + current_user.id.to_s, style: 'outline:none;active:none', class: 'nav-item nav-link text-white no-text-decoration' %>
						<%= link_to 'Chats', '/chats', class: 'nav-item nav-link no-text-decoration text-white' %>					
						<%= link_to 'Logout', sessions_destroy_path, class: 'nav-item nav-link text-white no-text-decoration' %>
						<% if current_user && current_user.admin? %>
							<%= link_to 'Admin panel', '/admin', class: 'nav-item nav-link text-white no-text-decoration' %>
						<% end %>
					<% else %>						
						<%= link_to 'Login', new_session_path, class: 'nav-item nav-link text-white' %>					
						<%= link_to 'Sign up', new_user_path, class: 'nav-item nav-link text-white' %>
					<% end %>

				</div>
			</div>
    </nav>

    <% if flash[:success] %>
      <div id="successflash" class="alert alert-success">
        <%= flash[:success] %>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div id="alertflash" class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>

		<div class="container mt-0 p-3">
    	<%= yield %>
		</div>

  </body>
</html>